name: "Helm template check"
description: "Verify helm generation template"
inputs:
  chart-path:
    description: Path of the helm chart
    required: false
    default: chart
  disable-checkout:
    description: Set to true to disable the code checkout step
    required: false
    default: false
  service-name:
    description: Defining service-name for charts
    required: true
    default: "${{ github.event.repository.name }}"
  values-staging:
    description: Helm values for staging
    required: true
    default: "chart/values-staging.yaml"
  values-production:
    description: Helm values for production
    required: true
    default: "chart/values-production.yaml"
runs:
  using: "composite"
  steps:
    - if: inputs.disable-checkout != 'true'
      name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Helm template (staging)
      shell: bash
      run: helm template ${{inputs.service-name}} ${{inputs.chart-path}} --debug -f ${{ inputs.values-staging }}
    - name: Helm template (production)
      shell: bash
      run: helm template ${{inputs.service-name}} ${{inputs.chart-path}} --debug -f ${{ inputs.values-production }}
